import { useEffect,useMemo,useState } from 'react';
import { renderSvg } from '@pcs/scene-core';
import type { Editor } from '../editor.js';
import { PLATFORMS } from '../targets/platforms.js';
import { getTarget } from '../targets/registry.js';
import { variantRecord } from '../targets/adapt.js';
import { batchAssessment,batchSummary,dataUrlBytes } from '../batch.js';
import { rasterizeSvg,exportBinaryPackage } from '../io.js';
import { collectPhotoData,inlinePhotos,buildExportPackage,ensureProjectDefaults } from '../github/export.js';
import { TargetPreview } from './TargetPreview.js';
import { TargetCapabilities } from './TargetCapabilities.js';
export function AdaptStudio({editor,onClose}:{editor:Editor;onClose:()=>void}){
 const [selected,setSelected]=useState([editor.exportTargetId]),[active,setActive]=useState(editor.exportTargetId),[photos,setPhotos]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[focal,setFocal]=useState({x:.5,y:.5});
 useEffect(()=>{let alive=true;void collectPhotoData(editor.currentProject()).then(v=>{if(alive)setPhotos(v);});return()=>{alive=false;};},[editor.doc]);
 const target=getTarget(active)!,assessment=useMemo(()=>batchAssessment(editor.doc,target),[editor.doc,target]),adapted=useMemo(()=>{const a=assessment.adapted;return {...a,document:applyFocus(a.document,focal)};},[assessment,focal]);
 function applyFocus(doc:typeof editor.doc,f:typeof focal){const copy=structuredClone(doc);const walk=(ls:any[])=>ls.forEach(l=>{if(l.type==='image'&&l.width>=doc.canvas.width*.9){l.focalX=f.x;l.focalY=f.y;}if(l.type==='group')walk(l.children);});walk(copy.layers);return copy;}
 const svg=(doc:typeof editor.doc)=>renderSvg(inlinePhotos(doc,photos),{time:(doc.animation?.duration??8)*.5});
 const src=(s:string)=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s);
 const saveVariant=()=>{const v=variantRecord(target.displayName,target.id,adapted.document,editor.project.createdAt);editor.setProjectMeta({variants:[...(editor.project.variants??[]),v]});setMessage('Independent variant saved in this project. Master preserved.');};
 const apply=()=>{const checkpoint={id:crypto.randomUUID(),name:'Before Smart Adapt',createdAt:new Date().toISOString(),document:structuredClone(editor.doc)};editor.setProjectMeta({history:[...(editor.project.history??[]),checkpoint].slice(-30)});editor.store.replaceDocument(adapted.document,'Smart Adapt '+target.displayName);editor.setExportTargetId(target.id);editor.setSelectedId(null);editor.requestFit();setMessage('Adapted canvas applied. Undo or the saved history checkpoint can restore the master.');};
 const generate=async()=>{setBusy(true);setMessage('');try{const files:Record<string,Uint8Array>={},manifest:any[]=[];const encoder=new TextEncoder();for(const id of selected){const t=getTarget(id)!;const a=batchAssessment(editor.doc,t),doc=applyFocus(a.adapted.document,focal);let rendered=svg(doc);const format=a.format;if(format==='jpg')rendered=rendered.replace(/(<svg[^>]*>)/,'$1<rect width="100%" height="100%" fill="#111827"/>');const data=await rasterizeSvg(rendered,doc.canvas.width,doc.canvas.height,{format,quality:.9}),bytes=dataUrlBytes(data);if(t.maxFileSizeMB&&bytes.length>t.maxFileSizeMB*1024*1024){manifest.push({target:id,status:'FILE_TOO_LARGE',bytes:bytes.length,limitMB:t.maxFileSizeMB});continue;}files[id+'.'+format]=bytes;manifest.push({target:id,status:a.status,format,bytes:bytes.length,warnings:a.warnings});await new Promise(r=>setTimeout(r,0));}
 const packageFiles=buildExportPackage({project:ensureProjectDefaults(editor.currentProject()),lightDark:false,includeWorkflow:false,animatedContribution:false,photoData:photos});files['ATTRIBUTIONS.md']=encoder.encode(packageFiles['ATTRIBUTIONS.md']??'No bundled photographs used. User assets retain their original rights.');files['export-manifest.json']=encoder.encode(JSON.stringify({createdAt:new Date().toISOString(),delivery:'Static images only; motion encoders unavailable',targets:manifest},null,2));const result=await exportBinaryPackage(files);setMessage(result?`Exported ${manifest.filter(m=>m.status!=='FILE_TOO_LARGE').length} variants. ${manifest.filter(m=>m.status==='FILE_TOO_LARGE').length} exceeded known limits and were skipped. Manifest and credits included. Existing files preserved.`:'Export cancelled.');}catch(e){setMessage('Export failed: '+String(e));}finally{setBusy(false);}};
 return <div className="adapt-studio pro-surface"><aside><h3>Export Everywhere</h3><p>Select destinations. Review each adapted composition before generating. Static images only; unverified rules remain your review decision.</p>{PLATFORMS.map(p=>{const a=batchSummary(editor.doc,p.target);return <div className={'adapt-target '+(p.id===active?'selected':'')} key={p.id}><input type="checkbox" aria-label={'Export to '+p.name} checked={selected.includes(p.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/><button onClick={()=>setActive(p.id)}><strong>{p.name}</strong><small>{a.status==='READY'?'✓ Ready':'⚠ Review composition / capability'} · {a.format.toUpperCase()}</small></button></div>;})}<button className="btn primary" disabled={busy||!selected.length} onClick={()=>void generate()}>{busy?'Generating sequentially…':`Generate ${selected.length} selected variants`}</button><p role="status">{message}</p></aside><main><header><h2>Smart Adapt</h2><button className="btn" onClick={onClose}>Back to export</button></header><div className="adapt-comparison"><figure><figcaption>Before · master preserved</figcaption><img src={src(svg(editor.doc))} alt="Smart Adapt master before"/></figure><figure><figcaption>After · {target.recommended.width}×{target.recommended.height}</figcaption><img src={src(svg(adapted.document))} alt="Smart Adapt after"/></figure></div><div className="adapt-actions"><label>Photo focal X<input type="range" aria-label="Adapt photo focal X" min="0" max="1" step=".01" value={focal.x} onChange={e=>setFocal({...focal,x:+e.target.value})}/></label><label>Photo focal Y<input type="range" aria-label="Adapt photo focal Y" min="0" max="1" step=".01" value={focal.y} onChange={e=>setFocal({...focal,y:+e.target.value})}/></label><button className="btn" onClick={saveVariant}>Save independent variant</button><button className="btn primary" onClick={apply}>Apply adapted canvas</button></div><ul>{adapted.changes.map(s=><li key={s}>{s}</li>)}{adapted.warnings.map(s=><li key={s} className="adapt-warning">⚠ {s}</li>)}</ul><TargetPreview key={target.id} target={target} src={src(svg(adapted.document))} profile={editor.project.platformProfiles?.[target.id]}/><TargetCapabilities target={target}/></main></div>;
}
