import {useEffect,useId,useRef,useState} from 'react';
import {Check,ChevronDown,Search} from 'lucide-react';
import {createPortal} from 'react-dom';
export function PCSSelect({label,value,options,onChange,disabled=false}:{disabled?:boolean;label:string;value:string;options:{value:string;label:string}[];onChange:(value:string)=>void}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[index,setIndex]=useState(0);
 const button=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null),id=useId();
 const filtered=options.filter(o=>o.label.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!button.current?.contains(e.target as Node)&&!popup.current?.contains(e.target as Node))setOpen(false);};const resize=()=>setOpen(false);window.addEventListener('pointerdown',close);window.addEventListener('resize',resize);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('resize',resize);};},[open]);
 useEffect(()=>{if(open)document.getElementById(id+'-'+index)?.scrollIntoView({block:'nearest'});},[index,open,id]);
 const rect=button.current?.getBoundingClientRect();
 const choose=(v:string)=>{onChange(v);setOpen(false);button.current?.focus();};
 return <><button ref={button} type="button" disabled={disabled} className="pcs-select-trigger" aria-label={label} aria-haspopup="listbox" aria-expanded={open} aria-controls={open?id:undefined} onClick={()=>{setQuery('');setIndex(0);setOpen(!open);}} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);}}}>{options.find(o=>o.value===value)?.label??value}<ChevronDown size={14}/></button>{open&&rect&&createPortal(<div ref={popup} className="pcs-select-popup" style={{left:Math.min(rect.left,Math.max(8,window.innerWidth-320)),top:Math.min(rect.bottom+6,Math.max(8,window.innerHeight-300)),width:Math.min(Math.max(rect.width,280),window.innerWidth-16)}} onKeyDown={e=>{if(e.key==='Tab'){setOpen(false);button.current?.focus();}if(e.key==='Home'){e.preventDefault();setIndex(0);}if(e.key==='End'){e.preventDefault();setIndex(Math.max(0,filtered.length-1));}if(e.key==='Escape'){e.preventDefault();setOpen(false);button.current?.focus();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(0,Math.min(filtered.length-1,i+(e.key==='ArrowDown'?1:-1))));}if(e.key==='Enter'&&filtered[index]){e.preventDefault();choose(filtered[index]!.value);}}}><label className="pcs-select-search"><Search size={14}/><input autoFocus aria-label={'Search '+label} role="combobox" aria-expanded={true} aria-controls={id} aria-activedescendant={filtered[index]?id+'-'+index:undefined} value={query} placeholder="Search…" onChange={e=>{setQuery(e.target.value);setIndex(0);}}/></label><div id={id} role="listbox" aria-label={label}>{filtered.map((o,i)=><button type="button" role="option" id={id+'-'+i} key={o.value} aria-selected={o.value===value} className={i===index?'focused':''} onMouseEnter={()=>setIndex(i)} onClick={()=>choose(o.value)}>{o.label}{o.value===value&&<Check size={14}/>}</button>)}{!filtered.length&&<p>No matches</p>}</div></div>,document.body)}</>;
}
