import {AppearanceEditor} from './AppearanceEditor.js';
import {StudioSelect} from './StudioSelect.js';
import { SupportPanel } from "./SupportPanel.js";
import { PCSLogo } from "./PCSLogo.js";
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Accessibility, ArrowUpRight, Brush, Database, Download, Info, Keyboard, Monitor, Moon, Play, Search, Settings2, ShieldCheck, Undo2, X } from 'lucide-react';
import { APP_VERSION, PRODUCT_NAME } from '../version.js';
import { DEFAULT_PREFS, setRuntimePrefs, type AppPrefs } from '../prefs.js';
import { STUDIO_THEMES, applyStudioTheme } from '../themes.js';
import { GitHubDataProvider, type GitHubUser } from '../github/provider.js';
import { connect, connectionState, deleteToken, storeToken, type ConnectionState } from '../github/connection.js';
import { buildCommands, type StudioActions } from '../commands.js';
import { bindingConflict, eventChord, readBindings, saveBindings, shortcutFor } from '../shortcuts.js';
import { loadJSON } from '../storage.js';
import '../styles/settings.css';
export { DEFAULT_PREFS }; export type { AppPrefs };
export function applyPrefs(p:AppPrefs):void {
 setRuntimePrefs(p);
 const root=document.documentElement;
 root.dataset.theme=p.theme;root.dataset.density=p.density;root.dataset.apptheme=p.appTheme;root.dataset.ambience=p.ambience;root.dataset.contrast=p.contrast;root.dataset.uiglow=p.uiGlow;
 root.classList.toggle('reduced-motion',p.reducedMotion);root.classList.toggle('high-contrast',p.highContrast);
 applyStudioTheme(p);
}
type Page='interface'|'editor'|'motion'|'shortcuts'|'export'|'appearance'|'accessibility'|'storage'|'github'|'application';
const GROUPS:Array<{group:string;pages:Array<[Page,string,typeof Monitor]>}>=[
 {group:'General',pages:[['interface','Interface & startup',Monitor]]},
 {group:'Editor',pages:[['editor','Canvas & selection',Settings2],['motion','Motion & playback',Play],['shortcuts','Keyboard shortcuts',Keyboard]]},
 {group:'Design & platform',pages:[['export','Export defaults',Download]]},
 {group:'Personalization',pages:[['appearance','Appearance',Brush],['accessibility','Accessibility',Accessibility]]},
 {group:'Data & services',pages:[['storage','Storage & recovery',Database],['github','GitHub connection',ShieldCheck]]},
 {group:'Application',pages:[['application','Updates & about',Info]]}
];
interface Setting {key:keyof AppPrefs;page:Page;label:string;hint:string;choices?:Array<[string,string]>;min?:number;max?:number;step?:number}
const SETTINGS:Setting[]=[
 {key:'density',page:'interface',label:'Interface density',hint:'Comfortable gives controls more room. Compact leaves more space for your design.',choices:[['comfortable','Comfortable'],['compact','Compact']]},
 {key:'defaultExperience',page:'interface',label:'Default controls',hint:'Simple shows common tools. Full exposes numerical transforms, effects and keyframes. Applied when Studio starts.',choices:[['quick','Simple'],['advanced','Full']]},
 {key:'showSmartGuides',page:'editor',label:'Smart alignment guides',hint:'Snap to canvas edges and center while dragging. Hold Alt to move freely.'},
 {key:'snapStrength',page:'editor',label:'Snapping distance',hint:'Distance in canvas pixels within which an object snaps to an alignment line.',min:0,max:24},
 {key:'loopPreview',page:'motion',label:'Loop animation preview',hint:'Repeat playback in Studio. The project’s exported animation loop is set in Motion.'},
 {key:'cardHoverAnimation',page:'motion',label:'Animate gallery previews',hint:'Play effect and scene previews while hovering their cards.'},
 {key:'exportFolder',page:'export',label:'Default output folder',hint:'Used as the starting location for native export dialogs. Leave empty for the system default.'},
 {key:'openFolderAfterExport',page:'export',label:'Open output folder',hint:'Reveal completed exports in Explorer.'},
 {key:'staticFallback',page:'export',label:'Include a static fallback',hint:'Profile packages also contain still versions of animated assets.'},
 {key:'theme',page:'appearance',label:'Appearance mode',hint:'System follows Windows. Light uses a bright workspace. Dark uses your selected palette; Frost and Studio Light are bright palettes.',choices:[['system','System'],['dark','Dark'],['light','Light']]},
 {key:'reducedMotion',page:'accessibility',label:'Reduce interface motion',hint:'Freeze gallery previews and interface motion. Project animation remains editable and can still be exported.'},
 {key:'highContrast',page:'accessibility',label:'High contrast controls',hint:'Make focus, borders and selections easier to distinguish.'},
 {key:'tooltipDelay',page:'accessibility',label:'Tooltip delay',hint:'Delay in milliseconds before control descriptions appear.',min:0,max:2000,step:50},
 {key:'autosaveInterval',page:'storage',label:'Recovery snapshot delay',hint:'Save one recovery draft after this many seconds without edits. Your original project file is not overwritten.',min:.5,max:15,step:.5},
 {key:'githubUsername',page:'github',label:'Default GitHub username',hint:'Used for new profile projects. Existing project usernames stay in Profile Designer.'}
];
const PAGE_NAMES=Object.fromEntries(GROUPS.flatMap(g=>g.pages.map(([id,label])=>[id,label])));
export function SettingsDialog({prefs,onChange,onResetLayout,onClose,onTutorial}:{prefs:AppPrefs;onTutorial:()=>void;onChange:(p:AppPrefs)=>void;onResetLayout:()=>void;onClose:()=>void}) {
 const [page,setPage]=useState<Page>('appearance'),[query,setQuery]=useState(''),[highlight,setHighlight]=useState(''),[token,setToken]=useState(''),[connection,setConnection]=useState<ConnectionState>({state:'disconnected'}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[cached,setCached]=useState<GitHubUser|null>(GitHubDataProvider.cachedFor(prefs.githubUsername)),[folder,setFolder]=useState('Browser local storage'),[draftTime,setDraftTime]=useState<number|null>(null),[bindings,setBindings]=useState(readBindings),[shortcutQuery,setShortcutQuery]=useState(''),[recording,setRecording]=useState<string|null>(null),[conflict,setConflict]=useState('');
 const commands=useMemo(()=>buildCommands({} as StudioActions),[]);
 useEffect(()=>{void connectionState().then(setConnection);void loadJSON<{ts:number}>('draft').then(d=>setDraftTime(d?.ts??null));if('__TAURI_INTERNALS__'in window)void import('@tauri-apps/api/path').then(p=>p.appDataDir()).then(setFolder);},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!recording)onClose();};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[onClose,recording]);
 const set=<K extends keyof AppPrefs>(key:K,value:AppPrefs[K])=>onChange({...prefs,[key]:value});
 const results=query.trim()?SETTINGS.filter(s=>`${s.label} ${s.hint} ${PAGE_NAMES[s.page]} ${s.key}`.toLowerCase().includes(query.toLowerCase())):[];
 const go=(s:Setting)=>{setPage(s.page);setQuery('');setHighlight(s.key);setTimeout(()=>document.getElementById(`preference-${s.key}`)?.scrollIntoView({block:'center',behavior:'smooth'}),30);setTimeout(()=>setHighlight(''),2200);};
 const rows=(which:Page)=>SETTINGS.filter(s=>s.page===which).map(s=><div id={`preference-${s.key}`} key={s.key} className={`preference-row ${highlight===s.key?'highlight':''}`}><label htmlFor={`control-${s.key}`}><strong>{s.label}</strong><span>{s.hint}</span></label><div className="preference-value">{s.choices?<div className="segmented">{s.choices.map(([value,label])=><button key={value} className={prefs[s.key]===value?'active':''} onClick={()=>set(s.key,value as never)}>{label}</button>)}</div>:typeof prefs[s.key]==='boolean'?<input id={`control-${s.key}`} aria-label={s.label} type="checkbox" checked={prefs[s.key] as boolean} onChange={e=>set(s.key,e.target.checked as never)}/>:typeof prefs[s.key]==='number'?<input id={`control-${s.key}`} aria-label={s.label} type="number" min={s.min} max={s.max} step={s.step??1} value={s.key==='autosaveInterval'?(prefs[s.key] as number)/1000:prefs[s.key] as number} onChange={e=>{const value=Number(e.target.value);if(Number.isFinite(value))set(s.key,(Math.min(s.max!,Math.max(s.min!,value))*(s.key==='autosaveInterval'?1000:1)) as never);}}/>:<input id={`control-${s.key}`} aria-label={s.label} value={prefs[s.key] as string} onChange={e=>set(s.key,e.target.value as never)}/>}<button className="preference-reset" title={`Reset ${s.label}`} aria-label={`Reset ${s.label}`} onClick={()=>set(s.key,DEFAULT_PREFS[s.key] as never)}><Undo2 size={13}/></button></div></div>);
 const resetCategory=()=>{const next={...prefs};for(const s of SETTINGS.filter(s=>s.page===page))(next[s.key] as unknown)=DEFAULT_PREFS[s.key];if(page==='appearance')Object.assign(next,{appTheme:DEFAULT_PREFS.appTheme,accent:'',contrast:'normal',uiGlow:'subtle',cursorGlow:'off',ambience:'none'});if(page==='shortcuts'){saveBindings({});setBindings({});}onChange(next);};
 async function refresh(){setBusy(true);const r=await GitHubDataProvider.fetchUser(prefs.githubUsername,{refresh:true});setCached(r.user);setMessage(r.error??(r.user?'Public data refreshed. Refresh your project in Profile Designer to apply it.':'Enter a username.'));setBusy(false);}
 const block=(title:string,children:ReactNode)=><section className="preference-card"><h3>{title}</h3>{children}</section>;
 return <div className="preferences-backdrop" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="preferences-window dialog" role="dialog" aria-modal="true" aria-label="Studio settings">
  <aside className="preferences-nav"><div className="preferences-brand"><Settings2 size={21}/><strong>Settings</strong></div><label className="preferences-search"><Search size={16}/><input aria-label="Search settings" placeholder="Search settings…" value={query} onChange={e=>setQuery(e.target.value)}/></label><nav>{GROUPS.map(g=><section key={g.group}><h2>{g.group}</h2>{g.pages.map(([id,label,Icon])=><button key={id} aria-current={page===id?'page':undefined} onClick={()=>{setPage(id);setQuery('');}}><Icon size={16}/><span>{label}</span></button>)}</section>)}</nav><small>Preferences save automatically.</small></aside>
  <div className="preferences-page"><header><div><h2>{query?'Search results':PAGE_NAMES[page]}</h2><p>Application preferences · your project content stays in the editor.</p></div><button className="icon-btn" aria-label="Close settings" onClick={onClose}><X size={20}/></button></header><div className="preferences-content" key={page}>
  {query?<div className="preferences-results">{results.length?results.map(s=><button key={s.key} onClick={()=>go(s)}><strong>{s.label}</strong><small>{PAGE_NAMES[s.page]}</small><p>{s.hint}</p><ArrowUpRight size={16}/></button>):<p>No settings match “{query}”.</p>}</div>:<>
  {page==='appearance'&&<>{block('Studio themes',<><p>Choose the environment around your artwork.</p><div className="theme-preview-grid">{STUDIO_THEMES.map(t=><button key={t.id} className={`theme-preview-card ${prefs.appTheme===t.id?'selected':''}`} aria-pressed={prefs.appTheme===t.id} onClick={()=>set('appTheme',t.id)}><div className="theme-mini" style={{background:t.root,color:t.text,borderColor:t.border}}><div className="theme-mini-top" style={{background:t.panel}}><i style={{background:t.accent}}/><span/><span/></div><div className="theme-mini-body"><div style={{background:t.panel}}><b/><b/><b/></div><div style={{background:t.canvas}}><div style={{background:t.raised,borderColor:t.accent}}><i style={{background:t.accent}}/><b/><b/></div></div><div style={{background:t.panel}}><b/><b/><b/></div></div><div className="theme-mini-timeline" style={{background:t.panel}}><i style={{background:t.accent}}/></div></div><span>{t.name}</span></button>)}</div></>)}<AppearanceEditor prefs={prefs} onChange={onChange}/>{block('Mode & accent',<>{rows('appearance')}<div className="preference-row"><label><strong>Accent color</strong><span>Highlights, selected items and focus rings.</span></label><div className="accent-presets"><button className="btn" onClick={()=>set('accent','')}>Palette default</button>{['#8dafff','#a78bfa','#df8bc3','#6ed7bf','#e8bb88'].map(c=><button aria-label={`Use accent ${c}`} aria-pressed={prefs.accent===c} key={c} style={{background:c}} onClick={()=>set('accent',c)}/>)}<input aria-label="Custom accent color" type="color" value={prefs.accent||STUDIO_THEMES.find(t=>t.id===prefs.appTheme)!.accent} onChange={e=>set('accent',e.target.value)}/></div></div></>)}<details className="preference-card"><summary>Advanced appearance</summary><p>Optional highlights around Studio controls. These never appear in exported artwork.</p>{(['contrast','uiGlow','cursorGlow'] as const).map(k=><div className="preference-row" key={k}><label>{k==='contrast'?'Panel contrast':k==='uiGlow'?'Control glow':'Cursor lighting'}</label><StudioSelect aria-label={k} value={prefs[k]} onChange={e=>set(k,e.target.value as never)}>{(k==='contrast'?['low','normal','high']:k==='uiGlow'?['off','subtle','strong']:['off','subtle','glow']).map(v=><option key={v}>{v}</option>)}</StudioSelect><button className="preference-reset" aria-label={`Reset ${k}`} onClick={()=>set(k,DEFAULT_PREFS[k])}><Undo2 size={13}/></button></div>)}</details></>}
  {page==='interface'&&<>{block('Workspace',rows(page))}{block('Getting started',<><p>Walk through import, scenes, background, text, layers, motion, profiles, preview and export. You can skip anytime.</p><button className="btn" onClick={()=>{onClose();onTutorial();}}>Restart startup tutorial</button></>)}</>}
  {page==='editor'&&<>{block('Alignment & selection',rows(page))}{block('Canvas navigation',<><p>Drag with the Hand tool (H) to pan. Ctrl + mouse wheel zooms. Ctrl+0 fits your artwork; Ctrl+1 shows actual size.</p><p>Safe areas start off. Enable them from View → Safe Areas when you need platform crop guidance.</p><button className="btn" onClick={onResetLayout}>Reset panel layout</button></>)}</>}
  {page==='motion'&&block('Preview playback',<>{rows(page)}<p>Space toggles animation playback while you are not typing. Use Motion for duration, tracks and keyframes. Full controls exposes detailed tracks.</p></>)}
  {page==='export'&&block('Output',rows(page))}
  {page==='accessibility'&&block('Comfort & visibility',rows(page))}
  {page==='storage'&&<>{block('Recovery',<>{rows(page)}<p>Last recovery snapshot: <strong>{draftTime?new Date(draftTime).toLocaleString():'No recovery draft saved yet'}</strong></p><p>PCS retains one current draft, recovered from the start screen. Save named projects to keep your own version history.</p></>)}{block('Local storage',<><code className="preferences-path">{folder}</code>{'__TAURI_INTERNALS__'in window&&<button className="btn" onClick={async()=>{const {invoke}=await import('@tauri-apps/api/core');await invoke('open_path',{path:folder});}}>Open data folder</button>}<div className="preference-row"><label><strong>GitHub cache</strong><span>Remove downloaded profile data. Your projects, credentials and exports are kept.</span></label><button className="btn" onClick={()=>{GitHubDataProvider.clearCache();setCached(null);setMessage('GitHub cache cleared.');}}>Clear safe cache</button></div></>)}</>}
  {page==='shortcuts'&&<>{block('Keyboard workflow',<><div className="shortcut-toolbar"><input aria-label="Search shortcuts" placeholder="Search commands or keys…" value={shortcutQuery} onChange={e=>setShortcutQuery(e.target.value)}/><StudioSelect aria-label="Shortcut preset" defaultValue="PCS" onChange={e=>{const next:Record<string,string>=e.target.value==='Figma'?{'view.fit':'Shift+1','view.actual':'Shift+0'}:{};saveBindings(next);setBindings(next);}}><option>PCS</option><option>Adobe-like</option><option>Figma</option></StudioSelect></div><p>Click a key to record a new shortcut. Escape cancels. Adobe-like shares PCS’s creative tool bindings; Figma changes canvas zoom shortcuts.</p>{conflict&&<p role="alert" className="preferences-warning">{conflict}</p>}{Array.from(new Set(commands.map(c=>c.group))).map(group=>{const filtered=commands.filter(c=>c.group===group&&`${c.label} ${shortcutFor(c)}`.toLowerCase().includes(shortcutQuery.toLowerCase()));return filtered.length?<div className="shortcut-group" key={group}><h4>{group}<button className="preference-reset" onClick={()=>{const next={...bindings};for(const c of commands.filter(c=>c.group===group))delete next[c.id];saveBindings(next);setBindings(next);}} aria-label={`Reset ${group} shortcuts`}><Undo2 size={13}/></button></h4>{filtered.map(c=><div className="shortcut-row" key={c.id}><span>{c.label}</span><button className="shortcut-key" onClick={()=>{setRecording(c.id);setConflict('');}} onKeyDown={e=>{if(recording!==c.id)return;e.preventDefault();e.stopPropagation();if(e.key==='Escape'){setRecording(null);return;}if(['Control','Shift','Alt','Meta'].includes(e.key))return;const chord=eventChord(e),other=bindingConflict(chord,c.id,commands);if(other){setConflict(`This shortcut is already used by ${other.label}.`);return;}const next={...bindings,[c.id]:chord};saveBindings(next);setBindings(next);setRecording(null);setConflict('');}}>{recording===c.id?'Press keys…':shortcutFor(c)||'Unassigned'}</button><button className="preference-reset" aria-label={`Reset shortcut for ${c.label}`} onClick={()=>{const next={...bindings};delete next[c.id];saveBindings(next);setBindings(next);}}><Undo2 size={13}/></button></div>)}</div>:null;})}</>)}</>}
  {page==='github'&&<>{block('Public profile',<>{rows(page)}<div className="service-status"><ShieldCheck size={23}/><div><strong>{connection.state==='connected'?`Authenticated as ${connection.login}`:connection.state==='unavailable'?'Public API · browser preview':'Public API · optional authentication not connected'}</strong><p>{cached?`CACHED · ${cached.login} · ${new Date(cached.fetchedAt).toLocaleString()}`:'No public profile cached for this username.'}</p></div></div><p>PCS reads public profile details, repositories and public activity from GitHub’s APIs. Data is cached on this computer. Export targets such as Discord and YouTube do not connect accounts.</p><div className="preferences-actions"><button className="btn" disabled={busy||!prefs.githubUsername} onClick={()=>void refresh()}>Refresh public data</button><button className="btn" onClick={()=>{GitHubDataProvider.clearCache();setCached(null);}}>Clear cache</button></div></>)}{block('Optional contribution calendar',<><p>GitHub’s GraphQL API requires authentication to read the calendar. Use a token with access to public profile data. Private contribution details are not requested. Credentials are stored in Windows Credential Manager, outside project files.</p>{connection.state==='unavailable'?<p>Secure credential storage is available in the native Studio app.</p>:connection.state==='connected'?<button className="btn" disabled={busy} onClick={async()=>{setBusy(true);const ok=await deleteToken();if(ok){setConnection({state:'disconnected'});GitHubDataProvider.clearCache();setCached(null);}setMessage(ok?'Disconnected. Credentials removed.':'Could not remove the credential.');setBusy(false);}}>Disconnect & remove token</button>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await connect(token);if(r.ok){const ok=await storeToken(token);setMessage(ok?'Connected. Refresh your profile to load the calendar.':'Windows could not securely store the token.');if(ok){setConnection({state:'connected',login:r.login!});GitHubDataProvider.clearCache();}}else setMessage(r.error??'Connection failed.');setToken('');setBusy(false);}}><input aria-label="GitHub token" type="password" autoComplete="off" placeholder="GitHub access token" value={token} onChange={e=>setToken(e.target.value)}/><button className="btn primary" type="submit" disabled={!token||busy}>Connect securely</button></form>}</>)}</>}
  {page==='application'&&<>{block('Updates',<><p>Studio <strong>{APP_VERSION}</strong></p><p>Download the main PCS app from the project's release page and extract the ZIP before running it. This app does not automatically download updates.</p></>)}{block('About',<div className="preferences-about"><PCSLogo boxed className="about-mark" /><h3>{PRODUCT_NAME}</h3><p>Make your profile yours.</p><p>Studio {APP_VERSION}</p><a href="https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme" target="_blank" rel="noreferrer">GitHub profile README documentation ↗</a><p>Open-source dependency licenses are included with the source project.</p></div>)}<SupportPanel/>{block('Advanced',<><p>Resetting preferences leaves projects, exports, the recovery draft and connected credentials untouched.</p><button className="btn danger" onClick={()=>{if(confirm('Reset all PCS preferences and keyboard shortcuts? Projects and credentials will be kept.')){saveBindings({});setBindings({});onChange({...DEFAULT_PREFS});onResetLayout();}}}>Reset all PCS preferences…</button></>)}</>}
  {message&&<p className="preferences-message" role="status">{message}</p>}<footer className="preferences-footer"><span>Changes apply automatically.</span><button className="btn ghost" onClick={resetCategory}><Undo2 size={14}/> Reset this page</button></footer>
  </>}
  </div></div>
 </div></div>;
}
