import {SceneImage} from './SceneImage.js';
import { useEffect, useState } from 'react';
import type { TargetDef } from '../targets/registry.js';
import type { PlatformProfile } from '../project.js';
import { getPlatform, visibleArea } from '../targets/platforms.js';
/** Original schematic layouts; no remote account data or proprietary artwork. */
export function TargetPreview({target,src,profile={},live=false}:{target:TargetDef;src:string;profile?:PlatformProfile;live?:boolean}){
 const platform=getPlatform(target.id),[mode,setMode]=useState<string>(platform.modes[0]!),[theme,setTheme]=useState<'dark'|'light'>('dark'),[guides,setGuides]=useState(true);
 useEffect(()=>setMode(getPlatform(target.id).modes[0]!),[target.id]);
 const kind=platform.renderer,area=visibleArea({...platform,target},mode),W=target.recommended.width,H=target.recommended.height;
 const name=profile.name||'Your name',handle=profile.handle||'yourhandle',bio=profile.bio||'Add your bio in the manual profile fields.',avatar=profile.avatar;
 const banner=<div className="platform-banner" style={{aspectRatio:`${area.width}/${area.height}`}}><SceneImage live={live} src={src} alt={`${target.displayName} converted upload`} style={{width:W/area.width*100+'%',maxWidth:'none',height:H/area.height*100+'%',left:-area.x/area.width*100+'%',top:-area.y/area.height*100+'%',position:'absolute',objectFit:'fill'}}/>{guides&&<svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" className="platform-guides" style={{width:W/area.width*100+'%',height:H/area.height*100+'%',left:-area.x/area.width*100+'%',top:-area.y/area.height*100+'%'}} aria-label="Safe areas and estimated avatar obstructions">{target.safeAreas.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.width} height={r.height} fill="none" stroke="#68f5b1" strokeWidth={Math.max(2,W/300)} strokeDasharray="14 8"><title>{r.note??'Safe area'}</title></rect>)}{target.avatarOverlaps?.map((r,i)=><rect key={'a'+i} x={r.x} y={r.y} width={r.width} height={r.height} fill="#ff9d6438" stroke="#ffb46e" strokeWidth={Math.max(2,W/300)}><title>{r.note??'Avatar obstruction estimate'}</title></rect>)}{target.safeAreas.map((r,i)=><text key={'label'+i} x={r.x+W*.008} y={r.y+W*.023} fontSize={Math.max(12,W*.016)} fill="#68f5b1" stroke="#101820" strokeWidth={Math.max(1,W*.001)} paintOrder="stroke">{r.note || 'Keep important text inside'}</text>)}</svg>}</div>;
 const identity=<div className="platform-identity"><span className="platform-avatar">{avatar?<img src={avatar} alt="Manually imported avatar"/>:name.charAt(0)}</span><div><h2>{name}</h2><span>@{handle}</span>{kind==='discord'&&<small>{profile.pronouns||'pronouns · optional'}</small>}</div>{['x','bluesky','facebook','linkedin','twitch'].includes(kind)&&<button type="button" disabled>Follow</button>}</div>;
 const links=(profile.links??'').split(/\n/).filter(Boolean);
 return <div className={`target-context platform-context platform-${kind} platform-${theme} platform-mode-${mode}`} style={{'--platform-accent':profile.accent||'#8b9dff'} as React.CSSProperties}>
 <header><strong>{target.displayName}</strong><span className="platform-level">{platform.level==='A'?'A · Connected':platform.level==='B'?'B · Manual profile':'C · Placement'}</span></header>
 <div className="platform-preview-tools"><div className="segmented" aria-label="Platform device">{platform.modes.map(d=><button key={d} aria-pressed={mode===d} className={mode===d?'active':''} onClick={()=>setMode(d)}>{d}</button>)}</div><button className="btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Light preview':'Dark preview'}</button><label><input type="checkbox" checked={guides} onChange={e=>setGuides(e.target.checked)}/> Safe zones</label></div>
 <article className="platform-page">
 {kind==='article'&&<><small>{target.displayName.split(' ')[0]} · Article</small><h2>{profile.featured||'Your next story'}</h2></>}
 {kind==='avatar'?<div className="platform-avatar-upload"><img src={src} alt="Profile photo crop"/><strong>{name}</strong><small>@{handle}</small></div>:banner}
 {platform.level==='B'&&<>{identity}<p className="platform-bio">{bio}</p>{links.length>0&&<div className="platform-links">{links.map((link,i)=><span key={i}>{link}</span>)}</div>}
 <nav className="platform-tabs" aria-label="Illustrated platform tabs">{(kind==='discord'?['About me','Connections']:kind==='youtube'?['Home','Videos','Shorts','Playlists','Community']:kind==='linkedin'?['About','Activity','Experience']:kind==='twitch'?['Home','About','Schedule','Videos']:kind==='portfolio'?['Work','About','Collections']:kind==='creator'?['Posts','Membership','About']:['Posts','Replies','Media']).map(t=><span key={t}>{t}</span>)}</nav>
 {kind==='discord'?<div className="platform-featured"><strong>ABOUT ME</strong><p>{bio}</p><strong>CONNECTIONS</strong><p>{profile.featured||'Add connections manually. Badges/effects are decorative previews, not earned account entitlements.'}</p></div>:<div className="platform-featured"><strong>{profile.featured||(kind==='youtube'?'Featured video / channel introduction':kind==='portfolio'?'Featured work':'Featured content')}</strong><div className="platform-content-grid"><i/><i/><i/></div></div>}</>}
 {platform.level==='C'&&<div className="platform-featured"><strong>{kind==='readme'?'README content':kind==='reddit'?'Community · posts and navigation':kind==='article'?'Article body':'Upload placement'}</strong><div className="platform-content-lines"><i/><i/><i/></div></div>}
 </article><small className="platform-disclaimer">{platform.help} Green: registry safe area. Amber: estimated UI obstruction. {target.verification==='unverified'?'Upload rules UNVERIFIED.':''}</small>
 </div>;
}
