[package]
license = "AGPL-3.0-only"
name = "pcs-launcher"
version = "0.3.3-dev"
edition = "2021"
description = "Profile Customization Studio Launcher — install, launch, update and repair the Studio."
build = "build.rs"

[dependencies]
pcs-launcher-core = { path = "../../crates/pcs-launcher-core" }
slint = "1"
open = "5"

[build-dependencies]
slint-build = "1"

embed-resource = "3.0.12"

