/**
 * Asset license manifest — every bundled external visual asset records
 * title, creator, source, license and attribution requirement.
 * The data lives in public/photos/licenses.json (generated by
 * scripts/fetch-photo-pack.mjs) so it ships with the app and is displayed
 * wherever an "Asset Info" control appears.
 */
export interface AssetLicense {
  file: string;
  title: string;
  creator: string;
  source: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
  attributionRequired: boolean;
  modified: string;
}

import licensesJson from "./photo-licenses.json";

export const LICENSES = licensesJson as AssetLicense[];

export function licenseFor(file: string): AssetLicense | undefined {
  return LICENSES.find((l) => l.file === file);
}

/** One-line human-readable attribution (used in Asset Info and exports). */
export function attributionLine(l: AssetLicense): string {
  return `${l.title} by ${l.creator} — ${l.source} — ${l.license}${l.attributionRequired ? " (attribution required)" : " (no attribution required)"}`;
}
