import {availablePackagePath} from '../src/exportPaths.js';
import {describe,it,expect} from 'vitest';
import {parseAppearance,parsePalette,paletteContrast,DEFAULT_APPEARANCE} from '../src/appearance.js';
import {profileIconSvg} from '../src/profileIcons.js';
import {buttonGraphic} from '../src/github/button-graphic.js';
import {buildExportPackage,ensureProjectDefaults} from '../src/github/export.js';
import {SCENE_LIBRARY} from '../src/sceneLibrary.js';
import {renderSvg} from '@pcs/scene-core';
import {profileStats,type GitHubUser} from '../src/github/provider.js';
import {DEFAULT_PREFS,validatePrefs,SETTINGS_SCHEMA_VERSION} from '../src/prefs.js';
describe('PCS 0.3.3 appearance and profile contracts',()=>{
 it('resets malformed appearance and clamps surface controls',()=>{expect(parseAppearance('{')).toEqual(DEFAULT_APPEARANCE);expect(parseAppearance({surface:'unknown',opacity:0,blur:Infinity})).toMatchObject({surface:'solid',opacity:.75,blur:12});});
 it('preserves safe custom themes through persisted preferences',()=>{const customAppearance=JSON.stringify({...DEFAULT_APPEARANCE,enabled:true,palette:{name:'Forest',colors:{panel:'#10231a',text:'#f1fff6'},background:''}});const result=validatePrefs({...DEFAULT_PREFS,customAppearance,settingsSchemaVersion:SETTINGS_SCHEMA_VERSION});expect(result.prefs.customAppearance).toBe(customAppearance);expect(parseAppearance(result.prefs.customAppearance).palette.colors.panel).toBe('#10231a');});
 it('rejects active backgrounds and CSS injection in imported themes',()=>{expect(parsePalette({colors:{panel:'url(javascript:1)'},background:'data:image/svg+xml,<svg onload="1"/>'})).toMatchObject({colors:{},background:''});expect(parsePalette({colors:{accent:'#00cc88'},background:'https://tracking.invalid/image.gif'}).colors.accent).toBe('#00cc88');});
 it('retains saved palettes and computes usable contrast ratios',()=>{expect(parseAppearance(JSON.stringify({...DEFAULT_APPEARANCE,saved:[{name:'Quiet',colors:{root:'#111111'},background:''}]})).saved[0]?.name).toBe('Quiet');expect(paletteContrast('#ffffff','#000000')).toBeCloseTo(21);expect(paletteContrast('#111111','#111111')).toBe(1);});
 it('renders icon paths and safely clamps color and size',()=>{const svg=profileIconSvg('heart',1000,'" onload="1');expect(svg).toContain('<path');expect(svg).toContain('width="128"');expect(svg).not.toContain('onload');expect(profileIconSvg('github')).toContain('M12 .8');});
 it('escapes custom button labels and retains requested geometry',()=>{const svg=buttonGraphic({label:'<script>&',url:'https://example.org',variant:'outline',radius:6,color:'#22aa77',icon:'heart'});expect(svg).toContain('&lt;script&gt;&amp;');expect(svg).toContain('fill="none"');expect(svg).toContain('rx="6"');expect(svg).not.toContain('<script>');});
 it('exports actual icon/button/image graphics without mutating project data',()=>{const bannerSpec=SCENE_LIBRARY[0]!.make(1200,400);const p=ensureProjectDefaults({name:'Test',bannerSpec} as any);p.readme={username:'yourname',assetsPrefix:'assets',sections:[{id:'icon',type:'icon',icon:'heart',label:'Hello'},{id:'picture',type:'image',src:'data:image/png;base64,AAAA',imageWidth:10,imageHeight:8},{id:'links',type:'buttons'}],buttons:[{label:'Visit',url:'https://example.org',variant:'outline',icon:'star'}]};const original=JSON.stringify(p);const files=buildExportPackage({project:p,lightDark:false,includeWorkflow:false,animatedContribution:false});expect(files['assets/block-0.svg']).toContain('<path');expect(files['assets/block-1.svg']).toContain('data:image/png;base64,AAAA');expect(files['assets/button-0.svg']).toContain('Visit');expect(files['README.md']).toContain('assets/block-0.svg');expect(files['README.md']).toContain('assets/button-0.svg');expect(JSON.stringify(p)).toBe(original);});
 it('never exports active or external image payloads as inline graphics',()=>{const p=ensureProjectDefaults({name:'Test',bannerSpec:SCENE_LIBRARY[0]!.make(1200,400)} as any);p.readme={username:'yourname',assetsPrefix:'assets',sections:[{id:'bad',type:'image',src:'data:image/svg+xml,<svg onload="alert(1)"/>'}]};const files=buildExportPackage({project:p,lightDark:false,includeWorkflow:false,animatedContribution:false});expect(files['assets/block-0.svg']).toBeUndefined();});
 it('derives rainy/snow/forest accents and centers ordinary scene text',()=>{for(const [name,color] of [['Rainy City Window','#ffd9a0'],['Snow Forest','#dfeaff'],['Forest Mist','#a8c3b1']]){const doc=SCENE_LIBRARY.find(s=>s.name===name)!.make(1200,400);expect(doc.brand?.accent).toBe(color);const title=doc.layers.find(l=>l.name==='Title') as any;expect(title.align).toBe('middle');expect(title.x).toBe(600);const subtitle=doc.layers.find(l=>l.name==='Subtitle') as any;expect(subtitle.align).toBe('middle');expect(subtitle.x).toBe(600);expect(renderSvg(doc,{time:1})).toContain(color);}});
 it('inherits a glow from the layer color when no blue was requested',()=>{const doc=SCENE_LIBRARY.find(s=>s.name==='Retro Terminal')!.make(1200,400);const svg=renderSvg(doc,{time:2});expect(svg).toContain('flood-color="#39d353"');expect(svg).not.toContain('flood-color="#5b8cff"');});
 it('samples atmosphere motion deterministically and keeps rain bounded',()=>{const doc=SCENE_LIBRARY.find(s=>s.name==='Rainy City Window')!.make(1200,400);expect(renderSvg(doc,{time:1})).not.toBe(renderSvg(doc,{time:2}));expect(renderSvg(doc,{time:1})).toBe(renderSvg(doc,{time:1}));expect(renderSvg(doc,{time:1}).length).toBeLessThan(250000);});
 it('labels primary language counts as loaded repositories and omits unavailable metrics',()=>{const u={publicRepos:30,followers:5,starsTotal:null,pullRequests:null,publicEvents:null,repos:[{language:'TypeScript'},{language:'TypeScript'},{language:null}]} as GitHubUser;const fields=profileStats(u);expect(fields.find(f=>f.key==='language-TypeScript')).toMatchObject({value:2,label:'TypeScript · loaded repos'});expect(fields.some(f=>f.key==='stars'||f.key==='prs'||f.key==='activity')).toBe(false);});
 it('preserves original files and all previous package companions on repeated export',async()=>{const used=new Set(['/exports/README.md','/exports/README.pcs.md','/exports/README.pcs-2.md','/exports/banner.svg','/exports/banner.pcs-new.svg']);const exists=async(p:string)=>used.has(p);expect(await availablePackagePath('/exports/README.md',true,exists)).toBe('/exports/README.pcs-3.md');expect(await availablePackagePath('/exports/banner.svg',false,exists)).toBe('/exports/banner.pcs-new-2.svg');expect(await availablePackagePath('/exports/new.svg',false,exists)).toBe('/exports/new.svg');});

});

it('preserves repeated Windows GIF and video exports',async()=>{const files=new Set(['C:/exports/banner.gif','C:/exports/banner.pcs-new.gif','C:/exports/banner.mp4']);expect(await availablePackagePath('C:\\exports\\banner.gif',false,async p=>files.has(p))).toBe('C:/exports/banner.pcs-new-2.gif');expect(await availablePackagePath('C:/exports/banner.mp4',false,async p=>files.has(p))).toBe('C:/exports/banner.pcs-new.mp4');});
